# Generated by Django 3.0.2 on 2020-02-01 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, choices=[('m', 'metre'), ('yd', 'yard'), ('kg', 'kilogram'), ('l', 'litre')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('color', models.CharField(choices=[('r', 'red'), ('g', 'green'), ('b', 'blue')], max_length=20)),
                ('other', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('gst_no', models.CharField(max_length=15)),
                ('other', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Goods')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Supplier')),
            ],
        ),
    ]
