# Generated by Django 3.0.2 on 2020-02-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='unit',
            field=models.CharField(blank=True, choices=[('kg', 'kilogram'), ('m', 'metre'), ('l', 'litre'), ('yd', 'yard')], max_length=2, null=True),
        ),
        migrations.RemoveField(
            model_name='gr',
            name='goods',
        ),
        migrations.AddField(
            model_name='gr',
            name='goods',
            field=models.ManyToManyField(to='core.Goods'),
        ),
    ]
