# Generated by Django 3.0.2 on 2020-02-01 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200201_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='unit',
            field=models.CharField(blank=True, choices=[('yd', 'yard'), ('kg', 'kilogram'), ('l', 'litre'), ('m', 'metre')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_article', to='core.Article'),
        ),
        migrations.AlterField(
            model_name='gr',
            name='goods',
            field=models.ManyToManyField(related_name='gr_goods', to='core.Goods'),
        ),
        migrations.AlterField(
            model_name='gr',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gr_supplier', to='core.Supplier'),
        ),
    ]
