# Generated by Django 3.0.2 on 2020-02-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200201_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='unit',
            field=models.CharField(blank=True, choices=[('l', 'litre'), ('yd', 'yard'), ('kg', 'kilogram'), ('m', 'metre')], max_length=2, null=True),
        ),
    ]
